dist: bionic

services:
  - postgresql
 
addons:
  postgresql: '9.5'
  apt:
    packages:
      - postgresql-9.5


branches:
  only:
    - "master"

language: python
python:
  - "3.8"

install:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then pip install -r requirements/dev.txt; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then pip install coveralls; fi

script:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then ./scripts/lib/run-ci; fi

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then coveralls; fi

notifications:
  email:
    recipients:
      - umair@fecundity.io
    on_success: always
    on_failure: always
