dist: bionic

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE $POSTGRES_DB;" -U postgres

addons:
  postgresql: '11'
  apt:
    packages:
      - postgresql-11
branches:
  only:
    - "master"

language: python
python:
  - "3.8"

install:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then pip install -r requirements/dev.txt; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then pip install coveralls; fi

script:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then ./scripts/lib/run-ci; fi

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then coveralls; fi

notifications:
  email:
    recipients:
      - mohsan@fecundity.io
    on_success: always
    on_failure: always

env:
  global:
    - POSTGRES_USER=root
    - POSTGRES_DB=fecundity
    - POSTGRES_PASSWORD=password123
    - POSTGRES_HOST=db
