version: '3.4'

services:
  db:
    image: postgres:9.5
    env_file:
      ./.env

  web:
    build:
      context: .
      target: prod
    volumes:
      - static_volume:/opt/fecundityllc/static

    env_file:
      ./.env

    container_name: trackit_staging
    command: ./scripts/lib/run-with-gunicorn 2
    depends_on:
      - db

volumes:
  static_volume:
