version: '3.4'

services:
  db:
    image: postgres:9.5
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: fecundity
      POSTGRES_PASSWORD: password123
      POSTGRES_HOST:db

  web:
    build:
      context: .
      target: dev

    env_file:
      ./.env.dev

    container_name: trackit
    command: ./scripts/lib/run-server
    volumes:
      - .:/opt/fecundityllc
    ports:
      - 8000:8000
    depends_on:
      - db
