#!/usr/bin/env bash
set -e

if [ -z "$COMPOSE_FILE" ]
then
    COMPOSE_FILE=docker-compose.prod.yml
fi

docker-compose -f $COMPOSE_FILE build
docker-compose -f $COMPOSE_FILE up -d --remove-orphans

docker-compose -f $COMPOSE_FILE exec -T -e DISABLE_ROUTER=1 web ./manage.py migrate
docker-compose -f $COMPOSE_FILE exec -T web ./manage.py collectstatic --noinput

docker-compose -f $COMPOSE_FILE restart nginx
