#!/usr/bin/env bash
set -e

version_file=version.py
current_version=$(cat $version_file)
echo "Current ${current_version}"

if [ -z "$1" ];
then
    echo "Empty version. Exiting...";
    exit 1
fi

version="version = '$1'"

echo "New ${version}"

msg="New version should be greater than old version."

if [[ "$version" < "$current_version" ]]; then
    echo $msg;
    exit 1;
elif [[ "$version" = "$current_version" ]]; then
    echo $msg;
    exit 1;
fi

git checkout master
git fetch origin
git rebase origin/master

echo $version > $version_file
git add $version_file
git commit -m "version: Bump to v$1."
git push origin
git push origin HEAD:staging
