#!/usr/bin/env bash
set -e
echo -e "\e[32mBuilding...\e[0m"
docker-compose build web > /dev/null

echo -e "\e[32mRunning tests...\e[0m"
docker-compose run --no-deps --rm web ./scripts/lib/run-tests "${@:1}"
echo -e "\e[32mOK!\e[0m"
